### ISSUE TITLE
Cannot find namespace 'firebase'

### ISSUE THREAD

**Issue by antonyfrance** [alexabbott/firebase-cms#19]
Hi what do think about 

ERROR in C:/Users/MAREUIL/backend/firecms/firebase-cms-master/src/app/storefront-components/product/product.component.ts (22,20): Cannot find namespace 'firebase'.
ERROR in C:/Users/MAREUIL/backend/firecms/firebase-cms-master/src/app/storefront-components/cart/cart.component.ts (20,20): Cannot find namespace 'firebase'.
ERROR in C:/Users/MAREUIL/backend/firecms/firebase-cms-master/src/app/storefront-components/cart-icon/cart-icon.component.ts (14,20): Cannot find namespace 'firebase'.

Best regards

**Comment by alexabbott** [comment]
@antonyfrance  Please try to add a firebase.d.ts reference on to typings.d.ts.

Just add the following line into the src/typings.d.ts file in your angular-cli project.

/// <reference path="../node_modules/firebase/firebase.d.ts" />
