### ISSUE TITLE
Angular v11 Update

### ISSUE THREAD

**Issue by wilsonsergio2500** [alexabbott/firebase-cms#28]
Hi @alexabbott 

I placed a pr for this update
https://github.com/alexabbott/firebase-cms/pull/27

I intent to continue updating the CMS if you are on board of course :-) 
Thanks

**Comment by alexabbott** [comment]
Thanks @wilsonsergio2500 ! I've merged your PR and am on board if you would like to continue working on this.

**Comment by wilsonsergio2500** [comment]
Thank you :-)
